[package]
name = "fundu"
version = "1.0.0"
edition = "2021"
authors = ["Joining7943 <joining@posteo.de>"]
description = "Configurable, precise and fast rust string parser to a Duration"
readme = "README.md"
license = "MIT"
keywords = ["fundu", "parse", "string", "duration", "time"]
categories = ["command-line-interface", "parsing", "date-and-time"]
homepage = "https://github.com/Joining7943/fundu"
repository = "https://github.com/Joining7943/fundu"
rust-version = "1.61.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
bench = false

[features]
default = ["standard"]
standard = []
custom = []
time = ["dep:time"]
chrono = ["dep:chrono"]
serde = ["dep:serde"]
with-iai = []
with-flamegraph = []

[dependencies]
time = { version = "<= 0.3.16", optional = true, default-features = false }
chrono = { version = "0.4.24", optional = true, default-features = false }
serde = { version = "1.0.162", optional = true, features=["derive"]}

[dev-dependencies]
rstest = "0.17.0"
rstest_reuse = "0.5.0"
criterion = "0.4.0"
chrono = { version = "0.4.23", default-features = false }
clap = { version = "<=4.3.2", features = ["cargo", "derive"] }
serde_test  = "1.0.162"

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11.0", features = ["flamegraph", "criterion"] }
inferno = { version = "=0.11.14" }
iai-callgrind = "0.3.1"

[profile.flamegraph]
inherits = "bench"
opt-level = 1
debug = true

[[bench]]
name = "benchmarks_custom"
harness = false
required-features = ["custom"]

[[bench]]
name = "benchmarks_standard"
harness = false
required-features = ["standard"]

[[bench]]
name = "iai_bench_parsing_time_units"
harness = false
required-features = ["standard", "with-iai"]

[[bench]]
name = "iai_bench_parsing"
harness = false
required-features = ["standard", "with-iai"]

[[bench]]
name = "iai_bench_parsing_negative"
harness = false
required-features = ["standard", "with-iai"]

[[bench]]
name = "iai_bench_parsing_infinity"
harness = false
required-features = ["standard", "with-iai"]

[[bench]]
name = "iai_bench_reference"
harness = false
required-features = ["with-iai"]

[[bench]]
name = "iai_bench_standard"
harness = false
required-features = ["standard", "with-iai"]

[[bench]]
name = "iai_bench_custom"
harness = false
required-features = ["custom", "with-iai"]

[[bench]]
name = "flamegraph_standard"
harness = false
bench = false
required-features = ["standard", "with-flamegraph"]

[[bench]]
name = "flamegraph_custom"
harness = false
bench = false
required-features = ["custom", "with-flamegraph"]

[[example]]
name = "simple"
test = true

[[example]]
name = "clap_derive"
test = true

[[example]]
name = "clap_builder"
test = true

[[example]]
name = "convert"
test = false
required-features = ["chrono", "time"]

[[example]]
name = "custom"
test = false
required-features = ["custom"]

[[example]]
name = "systemd"
test = false
required-features = ["custom"]

[[example]]
name = "gnu"
test = false
required-features = ["custom"]
