[workspace]

members = [
  "fundu",
  "fundu-systemd"
]

[workspace.dependencies]
chrono = { version = "0.4.24", default-features = false }
clap = "4.3.0"
criterion = "0.4.0"
iai-callgrind = "0.3.1"
inferno = "=0.11.14"
pprof = "0.11.0"
rstest = "0.17.0"
rstest_reuse = "0.5.0"
serde = { version = "1.0.162", features=["derive"]}
serde_test  = "1.0.162"
time = { version = "<= 0.3.20", default-features = false }
