[tool.bumpversion]
current_version = "0.4.1"
commit = true
tag = false
tag_name = "fundu-gnu-v{new_version}"
message = "Bump fundu-gnu version v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "fundu-gnu/Cargo.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "fundu-gnu/README.md"
search = 'fundu-gnu = "{current_version}"'
replace = 'fundu-gnu = "{new_version}"'
