[tool.bumpversion]
current_version = "1.85.0"
commit = true
message = "Bump MSRV v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "fundu/Cargo.toml"
search = 'rust-version = "{current_version}"'
replace = 'rust-version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "fundu-core/Cargo.toml"
search = 'rust-version = "{current_version}"'
replace = 'rust-version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "fundu-gnu/Cargo.toml"
search = 'rust-version = "{current_version}"'
replace = 'rust-version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "fundu-systemd/Cargo.toml"
search = 'rust-version = "{current_version}"'
replace = 'rust-version = "{new_version}"'

[[tool.bumpversion.files]]
filename = ".github/workflows/cicd.yml"

[[tool.bumpversion.files]]
glob = "**/README.md"

[[tool.bumpversion.files]]
filename = ".clippy.toml"
