name: Build and Check

on:
  push:
    branches: ["main", "cicd", "release", "develop"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      resetBenchmarks:
        description: "Reset the benchmark data"
        required: true
        type: boolean

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  BENCHMARK_REGRESSION_PERCENT_FAIL: 10

jobs:
  deny:
    name: Check dependencies/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "1.60.0"

  base:
    name: Build, check and test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain:
          - "1.60.0" # MSRV
          - stable
          - nightly
        include:
          - toolchain: "1.60.0"
            components: rustfmt
          - toolchain: nightly
            components: rustfmt
          - toolchain: stable
            components: rustfmt, clippy
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - name: Prepare
        if: matrix.toolchain != 'stable'
        run: |
          rustup toolchain install stable --no-self-update --component clippy
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: "${{ matrix.os }}_${{ matrix.toolchain }}"
      - name: Info if unix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          set -x
          uname -a
          pwd
          rustup --version
          rustup show
          rustup component list --installed
      - name: Info if windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        run: |
          set -x
          rustup show
          rustup component list --installed
      - name: Build
        run: cargo build --all-features
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo +stable clippy --all-features --all-targets -- -D warnings
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git # unstable on 1.66 + 1.67
      - name: Test
        run: cargo test --all-features

  cross:
    name: Cross build and test
    strategy:
      fail-fast: false
      matrix:
        target:
          ##### big endian targets #####
          - s390x-unknown-linux-gnu
          # - sparc64-unknown-linux-gnu
          # - powerpc-unknown-linux-gnu
          - mips-unknown-linux-gnu
          ##### little endian targets #####
          - i686-unknown-linux-gnu
          - i586-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          # - riscv64gc-unknown-linux-gnu
          # dependency errors: quick-xml
          # - wasm32-unknown-emscripten
          # dependency errors: criterion
          # - x86_64-linux-android
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.60.0"
      - name: Install cross
        run: |
          set -e
          mkdir -vp ~/.cargo/bin
          mkdir -vp ~/Downloads
          cd ~/Downloads
          wget -O cross.tar.gz https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz
          tar xvzf cross.tar.gz
          mv -v cross cross-util ~/.cargo/bin
      - name: Configure cross
        run: |
          cat <<EOF | tee Cross.toml
          [build.env]
          passthrough = ["CI", "RUST_BACKTRACE", "CARGO_TERM_COLOR", "CARGO_REGISTRIES_CRATES_IO_PROTOCOL", "CARGO_INCREMENTAL"]
          EOF
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: "ubuntu-latest_1.60.0_${{ matrix.target }}"
      - name: Info
        run: |
          set -x
          pwd
          rustup --version
          rustup show
          rustup component list --installed
          cargo --list
          cross --version
      - name: Build
        run: cross build --all-features --target ${{ matrix.target }}
      - name: Test
        run: cross test --all-features --target ${{ matrix.target }}

  docs:
    needs: [base, cross]
    name: Docs/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Run doc tests
        run: cargo test --all-features --doc
      - name: Check Documentation
        run: cargo doc --all-features --no-deps --document-private-items

  coverage:
    needs: [base, cross]
    name: Coverage/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Prepare
        run: sudo apt-get -y update && sudo apt-get -y install llvm
      - name: Info
        run: |
          set -x
          uname -a
          printenv | grep -i -e cargo -e rust -e llvm
          cargo -V
          rustup -V
          rustup show
          rustup component list --installed
      - name: Create coverage profile
        run: |
          cat <<EOF | tee ~/.cargo/config
          [profile.coverage]
          inherits = "dev"
          lto = false
          debug = true
          opt-level = 0
          EOF
      - name: Install grcov
        run: |
          cargo install rustfilt
          cargo install grcov
      - name: Clean
        run: cargo clean
      - name: Build
        run: cargo build --all-features --profile coverage
      - name: Test
        run: cargo test --all-features --tests --profile coverage
      - name: Generate code coverage
        run: |
          ~/.cargo/bin/grcov . \
            --llvm-path /usr/bin \
            --binary-path target/coverage \
            --ignore-not-existing \
            --output-type files \
            --excl-start "cov:\s*excl-start" \
            --excl-stop "cov:\s*excl-stop" \
            --excl-line '^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\(|.*//\s*cov:\s*excl-line)' \
            --ignore "examples/*" \
            --ignore build.rs \
            --ignore "vendor/*" \
            --ignore "/*" \
            --ignore "[a-zA-Z]:/*" \
            --source-dir . | sort -u

          ~/.cargo/bin/grcov . \
            --branch \
            --llvm-path /usr/bin \
            --binary-path target/coverage \
            --ignore-not-existing \
            --output-type lcov \
            --source-dir . \
            --excl-start "cov:\s*excl-start" \
            --excl-stop "cov:\s*excl-stop" \
            --excl-line '^\s*((debug_)?assert(_eq|_ne)?!|#\[derive\(|.*//\s*cov:\s*excl-line)' \
            --ignore "examples/*" \
            --ignore build.rs \
            --ignore "vendor/*" \
            --ignore "/*" \
            --ignore "[a-zA-Z]:/*" \
            --output-path lcov.info && test -e lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true
    env:
      RUSTFLAGS: "-C instrument-coverage"
      LLVM_PROFILE_FILE: "fundu_coverage-%p-%m.profraw"
      RUST_BACKTRACE: "0"

  fuzzing:
    needs: [base, cross]
    name: Fuzzy testing/ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./fuzz"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: llvm-tools
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          workspaces: |
            fuzz -> target
          cache-on-failure: true
      - name: Prepare
        run: sudo apt-get -y update && sudo apt-get -y install llvm
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Run fuzzing for 5 minutes
        run: |
          cargo fuzz run --all-features f64_like_input -- \
            -max_total_time=300 \
            -print_final_stats=1 \
            -print_corpus_stats=1 \
            -verbosity=2
    env:
      RUSTFLAGS: "-C instrument-coverage"
      LLVM_PROFILE_FILE: "fundu_fuzzy_coverage-%p-%m.profraw"

  benchmarks:
    needs: [base, cross]
    name: Benchmarks/ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - iai_bench_parsing
          - iai_bench_reference
          - iai_bench_time_unit_parsing
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.60.0"
      - name: Install iai-callgrind-runner
        run: cargo install iai-callgrind-runner
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Prepare
        run: sudo apt-get -y update && sudo apt-get -y install valgrind
      - name: Download reference benchmarks
        if: ${{ !inputs.resetBenchmarks }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          name: benchmarks-${{ matrix.benchmark }}
          check_artifacts: true
          path: target/iai
          if_no_artifact_found: warn
      - name: Run benchmark ${{ matrix.benchmark }}
        run: cargo bench --bench ${{ matrix.benchmark }} | tee bench.out
      - name: Check for regression
        run: |
          echo 0 > fail
          echo 0 > skip
          while IFS= read -r line; do
            skip=$(( $(< skip) > 0 ))
            if grep -Eq '^\S*reference$' --color=never <<<"$line"; then
              echo 5 > skip
            else
              echo $(( $(< skip) - 1 )) > skip
            fi
            if [[ $skip -eq 0 ]] && grep 'Estimated Cycles:' --color=never <<<"$line"; then
              p=$(sed -En 's/\s*Estimated Cycles:.*\([+]([0-9]*)([.][0-9]*)?%\)/\1/p' <<<"$line")
              if [[ $p -ge ${BENCHMARK_REGRESSION_PERCENT_FAIL} ]]; then
                echo "::error::Regressed +${p}% >= BENCHMARK_REGRESSION_PERCENT_FAIL (=${BENCHMARK_REGRESSION_PERCENT_FAIL}%)"
                echo 2 > fail
              fi
            else
              echo "$line"
            fi
          done < bench.out
          exit $(< fail)
      - uses: actions/upload-artifact@v3
        with:
          name: benchmarks-${{ matrix.benchmark }}
          path: target/iai
