name: Deploy
on:
  push:
    tags:
      - "fundu-systemd-v*"

jobs:
  publish:
    name: Publish fundu-systemd to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish --package fundu-systemd --token ${{ secrets.CRATES_GITHUB_TOKEN }}
