name: Deploy
on:
  push:
    tags:
      - "fundu-gnu-v*"

jobs:
  publish:
    name: Publish fundu-gnu to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Publish
        run: cargo publish --package fundu-gnu --token ${{ secrets.CRATES_GITHUB_TOKEN }}
